coded aperture:
  number of pixels along X: 21
  number of pixels along Y: 21
  pixel size along X: 400
  pixel size along Y: 400
detector:
  number of pixels along X: 112
  number of pixels along Y: 112
  pixel size along X: 71
  pixel size along Y: 71
infos:
  system name: HYACAMEO
spectral range:
  number of spectral samples: 10
  wavelength max: 650
  wavelength min: 450
system architecture:
  dispersive element:
    A1: 23.854179544175658
    A2: 37.661598196653195
    A3: 23.854179544175658
    alpha_c: 4.83674936875987
    catalog: Schott
    delta alpha c: 0
    delta beta c: 0
    glass1: N-SK2
    glass2: N-SF4
    glass3: N-SK2
    type: amici
    wavelength center: 520.0
  focal lens: 75000
  system type: DD-CASSI
